### ISSUE TITLE
Plans for supporting Windows?

### ISSUE THREAD

**Issue by jamesnunn** [tk0miya/testing.postgresql#2]
I notice that there are no references to search paths for Windows - is this planned?

**Comment by tk0miya** [comment]
I have no plan to do that. but any pull requests are welcomed.

**Comment by fleimgruber** [comment]
@jamesnunn I would like to have a look at it and see how much effort it would be. Did you investigate this further?

**Comment by jamesnunn** [comment]
Hi, actually I found this really useful but wasn't able to successfully port your code to Windows `os.fork` being the main culprit. I ended up writing my own: https://github.com/jamesnunn/pgtest

**Comment by fleimgruber** [comment]
Yes, I had a quick look too, and considered it quite doomed with `os.fork` being there. Thanks for letting me know about your own take on it, will check it out first thing on Monday.
